config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:name, :done)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <%= f.label :done %>:
  <%= f.text_field :done %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<h1>Here are all your tasks:</h1>
<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <p><%= task.done %></p>
  <p><%= link_to "Delete", task_path(task), method: :delete, data: {confirm: "Are you sure?"} %></p>
  <p><%= link_to "New", new_task_path %></p>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.done %></p>